---
title: "ARIMA stock analysis"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
library(prophet)
library(quantmod)
library(forecast)
library(xts)
library(tseries)
library(timeSeries)
library(dplyr)
library(fGarch)

start <- as.Date("2010-05-27")
end <- as.Date("2020-05-27")

getSymbols("AAPL",src = "yahoo",from = start, to = end)

class(AAPL)

head(AAPL)


getSymbols(c("MSFT", "GOOG", "AMZN","NDAQ"), src = "yahoo", from = start, to = end)

plot(AAPL[, "AAPL.Close"], main = "AAPL", col = "red" )
plot(AMZN[, "AMZN.Close"], main = "AMZN", col = "red")
plot(GOOG[, "GOOG.Close"], main = "GOOG", col = "red")
plot(MSFT[, "MSFT.Close"], main = "MSFT", col = "red")
plot(NDAQ[, "NDAQ.Close"], main = "NDAQ", col = "red")

candleChart(AAPL, up.col = "red", dn.col = "white", theme = "white")
candleChart(AMZN, up.col = "red", dn.col = "white", theme = "white")
candleChart(GOOG, up.col = "black", dn.col = "red", theme = "white")
candleChart(MSFT, up.col = "black", dn.col = "red", theme = "white")
candleChart(NDAQ, up.col = "black", dn.col = "red", theme = "white")


summary(AAPL)
summary(AMZN)
summary(GOOG)
summary(MSFT)
summary(NDAQ)

#computing rates of change

#Apple

ROCapple <- ROC(AAPL[, "AAPL.Close"], n=1,)
head(ROCapple)
plot(ROCapple, col="red")

#amazon

ROCamazon <- ROC(AMZN[, "AMZN.Close"], n=1,)
head(ROCamazon)
plot(ROCamazon, col="red")
     
#google

ROCgoogle <- ROC(GOOG[, "GOOG.Close"], n=1,)
head(ROCgoogle)
plot(ROCgoogle, col="red")
     
#micosoft

ROCmicrosoft <- ROC(MSFT[, "MSFT.Close"], n=1,)
head(ROCmicrosoft)
plot(ROCmicrosoft, col="red")
     
#NASDAQ

ROCnasdaq <- ROC(NDAQ[, "NDAQ.Close"], n=1,)
head(ROCnasdaq)
plot(ROCnasdaq, col="red")

#combining all roc plots

roc <- as.xts(data.frame(AAPL = ROCapple, MSFT = ROCmicrosoft, GOOG = ROCgoogle, AMZN = ROCamazon, NDAQ = ROCnasdaq))
plot(as.zoo(roc), screens = 1,col = c("red","blue","green","black","Purple"), ylab = "Rate of Change", xlab = "Time in Years")
legend("bottomleft", c("AAPL", "MSFT", "GOOG", "AMZN", "NDAQ"), col=c("red","blue","green","black","Purple"), lty = 1:3, cex = 0.5)


# Create an xts object (xts is loaded with quantmod) that contains closing
# prices for AAPL, MSFT, and GOOG
stocks <- as.xts(data.frame(AAPL = AAPL[, "AAPL.Close"], MSFT = MSFT[, "MSFT.Close"], 
                            GOOG = GOOG[, "GOOG.Close"], AMZN = AMZN[, "AMZN.Close"], NDAQ = NDAQ[, "NDAQ.Close"]))
head(stocks)

#Saving into CSV
write.csv(stocks, file = "stocks.csv", row.names = FALSE)
setwd("C:/Users/ziyad/Desktop/Data Analytics capstone")

# Create a plot showing all series as lines; must use as.zoo to use the zoo
# method for plot, which allows for multiple series to be plotted on same
# plot

plot(as.zoo(stocks), screens = 1, lty = 1:3,col = c("red","blue","green","black","Purple"), xlab = "Date", ylab = "Price in $")
legend("left", c("AAPL", "MSFT", "GOOG", "AMZN", "NDAQ"), col=c("red","blue","green","black","Purple"), lty = 1:3, cex = 0.5)

#get pipe operator

if (!require("magrittr")) {
  install.packages("magrittr")
  library(magrittr)
}

nominal_return = apply(stocks, 1, function(x) {x / stocks[1,]*100}) %>% 
  t %>% as.xts

head(nominal_return)

plot(as.zoo(nominal_return), screens = 1, lty = 1:3, xlab = "Date", ylab = "% Return on initial investment", col = c("red","blue","green","black","purple"))
legend("topleft", c("AAPL", "MSFT", "GOOG","AMZN","NDAQ"),col = c("red","blue","green","black","purple"), lty = 1:3, cex = 0.5)


#Testing out ARIMA models with closing value on Y axis and Date on x axis

#1) Apple

class(AAPL)

AAPL_close_price <- (AAPL[,4])
plot((AAPL_close_price))
class(AAPL_close_price)
par(mfrow = c(1,1))
print(adf.test(AAPL_close_price)) #P-value > 0.05 indicates non stationary data
auto.arima(AAPL_close_price, seasonal = FALSE)
par(mfrow = c(2,2))
pacf(AAPL_close_price)
acf(AAPL_close_price)

#Translating Raw price into logarithmic form to obtain returns

lnapple = log(AAPL_close_price)
print(lnapple[1:10])

#Checking for stationarity

acf(lnapple, lag.max = 200,  main = "ACF for Apple Series")
pacf(lnapple, lag.max = 200, main = "PACF for Apple Series")
print(adf.test(lnapple)) #P-value > 0.05 indicates non stationary data

#Differencing the data to turn into stationary data

difflnapple = diff(lnapple,)
head(difflnapple)
adf.test(lnapple)
adf.test(difflnapple[2:1259,]) # p-value < 0.05 indication stationary data. Model fitting to continue

#Trying different fits

fitA = auto.arima(AAPL_close_price, seasonal = FALSE)
tsdisplay(residuals(fitA), lag.max = 40, main = '1,1,0 Model Residuals')
auto.arima(AAPL_close_price, seasonal = FALSE)

fitB = arima(AAPL_close_price, order = c(1,1,19))
tsdisplay(residuals(fitB), lag.max = 40, main = '(1,1,19) Model Residuals')

fitC = arima(AAPL_close_price, order = c(1,1,28))
tsdisplay(residuals(fitC), lag.max = 40, main = '(1,1,28) Model Residuals')

fitD = arima(AAPL_close_price, order = c(1,2,40))
tsdisplay(residuals(fitD), lag.max = 40, main = '(1,2,40) Model Residuals')


par(mfrow = c(2,2))
term <- 730
fcast1 <- forecast(fitA, h = term)
plot(fcast1)
fcast2 <- forecast(fitB, h = term)
plot(fcast2)
fcast3 <- forecast(fitC, h = term)
plot(fcast3)
fcast4 <- forecast(fitD, h = term)
plot(fcast4)
print(fcast4)

#2) Amazon

class(AMZN)

AMZN_close_price <- (AMZN[,4])
plot((AMZN_close_price))
class(AMZN_close_price)
print(adf.test(AMZN_close_price)) #P-value > 0.05 indicates non stationary data
auto.arima(AMZN_close_price, seasonal = FALSE)
par(mfrow = c(2,2))
pacf(AMZN_close_price)
acf(AMZN_close_price)

#Translating Raw price into logarithmic form to obtain returns

lnamzn = log(AMZN_close_price)
head(lnamzn)

#Checking for stationarity

par(mfrow = c(2,2))
acf(lnamzn, lag.max = 200,  main = "ACF for Amazon Series")
pacf(lnamzn, lag.max = 200, main = "PACF for Amazon Series")
print(adf.test(lnamzn)) #P-value > 0.05 indicates non stationary data

#Differencing the data to turn into stationary data

difflnamzn = diff(lnamzn,)
head(difflnamzn)
adf.test(lnamzn)
adf.test(difflnamzn[2:1259,]) # p-value < 0.05 indication stationary data. Model fitting to continue

#Trying different fits

fitA = auto.arima(AMZN_close_price, seasonal = FALSE)
tsdisplay(residuals(fitA), lag.max = 40, main = '0,1,1 Model Residuals')
auto.arima(AMZN_close_price, seasonal = FALSE)

fitB = arima(AMZN_close_price, order = c(1,1,19))
tsdisplay(residuals(fitB), lag.max = 40, main = '(1,1,19) Model Residuals')

fitC = arima(AMZN_close_price, order = c(1,1,28))
tsdisplay(residuals(fitC), lag.max = 40, main = '(1,1,28) Model Residuals')

fitD = arima(AMZN_close_price, order = c(1,2,40))
tsdisplay(residuals(fitD), lag.max = 40, main = '(1,2,40) Model Residuals')


par(mfrow = c(2,2))
term <- 730
fcast1 <- forecast(fitA, h = term)
plot(fcast1)
fcast2 <- forecast(fitB, h = term)
plot(fcast2)
fcast3 <- forecast(fitC, h = term)
plot(fcast3)
fcast4 <- forecast(fitD, h = term)
plot(fcast4)
print(fcast4)


#3) Google

class(GOOG)

GOOG_close_price <- (GOOG[,4])
plot((GOOG_close_price))
class(GOOG_close_price)
print(adf.test(GOOG_close_price)) #P-value < 0.05 indicates stationary data
auto.arima(GOOG_close_price, seasonal = FALSE)
par(mfrow = c(2,2))
pacf(GOOG_close_price)
acf(GOOG_close_price)


#Trying different fits

fitA = auto.arima(GOOG_close_price, seasonal = FALSE)
tsdisplay(residuals(fitA), lag.max = 40, main = '0,1,1 Model Residuals')
auto.arima(GOOG_close_price, seasonal = FALSE)

fitB = arima(GOOG_close_price, order = c(1,1,19))
tsdisplay(residuals(fitB), lag.max = 40, main = '(1,1,19) Model Residuals')

fitC = arima(GOOG_close_price, order = c(1,1,28))
tsdisplay(residuals(fitC), lag.max = 40, main = '(1,1,28) Model Residuals')

fitD = arima(GOOG_close_price, order = c(1,2,40))
tsdisplay(residuals(fitD), lag.max = 40, main = '(1,2,40) Model Residuals')


par(mfrow = c(2,2))
term <- 730
fcast1 <- forecast(fitA, h = term)
plot(fcast1)
fcast2 <- forecast(fitB, h = term)
plot(fcast2)
fcast3 <- forecast(fitC, h = term)
plot(fcast3)
fcast4 <- forecast(fitD, h = term)
plot(fcast4)
print(fcast4)


#4) Microsoft

class(MSFT)

MSFT_close_price <- (MSFT[,4])
plot((MSFT_close_price))
class(MSFT_close_price)

print(adf.test(MSFT_close_price)) #P-value > 0.05 indicates non stationary data
auto.arima(MSFT_close_price, seasonal = FALSE)
par(mfrow = c(2,2))
pacf(MSFT_close_price)
acf(MSFT_close_price)

#Translating Raw price into logarithmic form to obtain returns

lnMSFT = log(MSFT_close_price)
head(lnMSFT)

#Checking for stationarity

par(mfrow = c(2,2))
acf(lnMSFT, lag.max = 200,  main = "ACF for Microsoft Series")
pacf(lnMSFT, lag.max = 200, main = "PACF for Microsoft Series")
print(adf.test(lnMSFT)) #P-value > 0.05 indicates non stationary data

#Differencing the data to turn into stationary data

difflnMSFT = diff(lnMSFT,)
head(difflnMSFT)
adf.test(lnMSFT)
adf.test(difflnMSFT[2:1259,]) # p-value < 0.05 indication stationary data. Model fitting to continue


#Trying different fits

fitA = auto.arima(MSFT_close_price, seasonal = FALSE)
tsdisplay(residuals(fitA), lag.max = 40, main = '3,1,1 Model Residuals')
auto.arima(MSFT_close_price, seasonal = FALSE)

fitB = arima(MSFT_close_price, order = c(1,1,19))
tsdisplay(residuals(fitB), lag.max = 40, main = '(1,1,19) Model Residuals')

fitC = arima(MSFT_close_price, order = c(1,1,28))
tsdisplay(residuals(fitC), lag.max = 40, main = '(1,1,28) Model Residuals')

fitD = arima(MSFT_close_price, order = c(1,2,40))
tsdisplay(residuals(fitD), lag.max = 40, main = '(1,2,40) Model Residuals')


par(mfrow = c(2,2))
term <- 730
fcast1 <- forecast(fitA, h = term)
plot(fcast1)
fcast2 <- forecast(fitB, h = term)
plot(fcast2)
fcast3 <- forecast(fitC, h = term)
plot(fcast3)
fcast4 <- forecast(fitD, h = term)
plot(fcast4)
print(fcast4)


#5) Nasdaq

class(NDAQ)

NDAQ_close_price <- (NDAQ[,4])
plot((NDAQ_close_price))
class(NDAQ_close_price)

print(adf.test(NDAQ_close_price)) #P-value < 0.05 indicates stationary data
auto.arima(NDAQ_close_price, seasonal = FALSE)
par(mfrow = c(2,2))
pacf(NDAQ_close_price)
acf(NDAQ_close_price)


#Trying different fits

fitA = auto.arima(NDAQ_close_price, seasonal = FALSE)
tsdisplay(residuals(fitA), lag.max = 40, main = '4,1,4 Model Residuals')
auto.arima(NDAQ_close_price, seasonal = FALSE)

fitB = arima(NDAQ_close_price, order = c(1,1,19))
tsdisplay(residuals(fitB), lag.max = 40, main = '(1,1,19) Model Residuals')

fitC = arima(NDAQ_close_price, order = c(1,1,28))
tsdisplay(residuals(fitC), lag.max = 40, main = '(1,1,28) Model Residuals')

fitD = arima(NDAQ_close_price, order = c(1,2,40))
tsdisplay(residuals(fitD), lag.max = 40, main = '(1,2,40) Model Residuals')


par(mfrow = c(2,2))
term <- 730
fcast1 <- forecast(fitA, h = term)
plot(fcast1)
fcast2 <- forecast(fitB, h = term)
plot(fcast2)
fcast3 <- forecast(fitC, h = term)
plot(fcast3)
fcast4 <- forecast(fitD, h = term)
plot(fcast4)
print(fcast4)








